### ISSUE TITLE
Number of threads don't change

### ISSUE THREAD

**Issue by Davood-Norouzi** [pinellolab/CRISPRme#20]
Thank you for this great tool!

I run this command:

>> nohup crisprme.py complete-search --genome Genomes/hg38/ --vcf list_vcf.txt/ --guide New_guides.txt --pam PAMs/20bp-NGG-SpCas9.txt --annotation Annotations/encode+gencode.hg38.bed --samplesID list_samplesID.txt --gene_annotation Annotations/gencode.protein_coding.bed --bMax 2 --mm 6 --bDNA 2 --bRNA 2 --merge 3 --output New --thread 64 &

I use --thread 64, but the code is still only using 4 cores. How do I change the number of cores utilized?

Also, what does --merge do? I couldn't find that in the --help section.

Thanks again,
-Davood

**Comment by lindayqlin** [comment]
Hi Davood,

Thank you for using CRISPRme! 

Can you let us know which version you're running please? We recently released v2.1.0 which hopefully fixes this bug for the most part and should support a custom number of threads for the search. (We still have some steps in our workflow which are currently constrained to use only 4 threads due to memory management, but we plan to remove these constraints in the near future to further boost the search speed.) 

--merge specifies the window (# of nucleotides) within which to merge candidate off-targets since the initial search generates many results with only slightly different alignments all within the same genomic window if bulges are allowed. Our main output file contains all the highest scoring candidate off-targets after merging with a given genomic window represented only once. (We also output a file containing all the merged off-targets not included in our main output in case those are of interest too.) We will add this to the help section -- thanks for catching this omission.

Hope this helps and please let us know if you have any further questions!
Linda

**Comment by Davood-Norouzi** [comment]
Thanks Linda for the quick response!

When I update via conda (conda update crisprme), the version I get is still v2.0.9. Hope newer version will be available soon on bioconda.

Davood

**Comment by lindayqlin** [comment]
Hi Davood,

It appears that this might be an issue with Bioconda when trying to update packages hosted on their servers. In the meantime, running `mamba install crisprme==2.1.0` (mamba is like conda with faster dependency solving) should work to get the latest version. Please let us know if that works for you!

That command should generate images -- no specific flags are needed. Are you missing the `imgs` folder in the Results or is it empty? (And does the rest of the output look as expected?)

Thanks in advance,
Linda

**Comment by Davood-Norouzi** [comment]
Thanks Linda!

Upgrading to version 2.1.0, fixed the missing images issue. One final inquiry, can you point me to the part of the code that sets the resolution (dpi) of the produced images. It would be very helpful if we could have access to such settings.

-Davood

**Comment by lindayqlin** [comment]
Wonderful, thanks for letting us know! 

Of course, that should be the `plt.rcParams["figure.dpi"]` lines in PostProcess/CRISPRme_plots.py for the main results plots (or PostProcess/populations_distribution.py for population distribution plots).

Hope this helps!
Linda

**Comment by Davood-Norouzi** [comment]
Excellent! One last question Linda, do you have a recommendation for the on-target (guide selection) step? Broad institute tools, usually generate some on target efficiency scores and off target tier-I (coding region), tier-II (intronic regions), ... information. Can we get similar information from Crisprme?

**Comment by lindayqlin** [comment]
CRISPRme is intended as an off-target nomination tool so we do not calculate an on-target efficiency score, but for off-target potential, we would suggest to look at our aggregated specificity score as well as at annotations for the top candidate off-targets in the results.

At the moment, you can find the specificity score (range [0,1] where 1 would be a gRNA with no off-targets) in the file `.*acfd*.txt` (for example, you should have the file `.New.acfd_CFD.txt` from your command above) and the annotations from GENCODE & ENCODE in the results columns. 

We are currently working on also outputting a summary file of the search results (which would include the specificity score), as well as plots that will allow easier visualization of how often and which candidate off-targets occur in notable genomic regions.

Hope this helps!
Linda
