### ISSUE TITLE
PAM input format

### ISSUE THREAD

**Issue by dsantesmasses** [pinellolab/CRISPRme#29]
Hi,

What is the format for the file containing the pam, eg. `PAMs/20bp-NGG-spCas9.txt`. I don't seem to find a description of this file.

Thanks!

**Comment by ManuelTgn** [comment]
Hi @dsantesmasses,

thank you for using CRISPRme in your research!
In order to ensure proper formatting, the PAM file should contain the full PAM sequence and the PAM length, with a space separator between the two. For example, if you're using the spCas9 with a 20bp NGG PAM sequence, your file should look something like this:
```
NNNNNNNNNNNNNNNNNNNNNGG 3
```
As an additional resource, I've attached a sample file for the spCas9 NGG PAM, which you can find at the following link: [20bp-NGG-SpCas9.txt](https://github.com/pinellolab/CRISPRme/files/11056931/20bp-NGG-SpCas9.txt). This should give you a good idea of how to format your own PAM file. Let us know if you have any questions! 

Best,
Manuel
