### ISSUE TITLE
Question about web portal vs. running CRISPRme locally

### ISSUE THREAD

**Issue by danjweiner** [pinellolab/CRISPRme#41]
Hello,

Thank you for creating this useful tool. I had a quick question: if I ran CRISPRme with parameters X on the web portal and then ran it locally with the same parameters X, should I expect the integrated_results file that is output to be identical? I was specifically wondering if there was any output truncation that happened on the web portal for efficiency even with the integrated_results file (which I think is the complete off-target set).

Thank you

**Comment by samuelecancellieri** [comment]
Hello @danjweiner 
the web portal runs an identical version of the software with respect to the local package, but due to updates if you run the two search in different times it can be possible to obtain slightly different results.
Other than that, no file truncation happens in the web portal version, so the file you obtain as results (the integrated_results) is the complete one.

If you have any more questions, don't hesitate to ask.

Best,
