### ISSUE TITLE
Usage for nucleases other than cas9

### ISSUE THREAD

**Issue by thomas-davis** [pinellolab/CRISPRme#60]
Can crisprme be used for prediction for non-cas9 nucleases?

I understand crisprme does not compute cfd score in these cases, but that crisprme uses CFD for selecting deduplicating targets for the bestMerge file. What does the tool do when CFD is not computable?

**Comment by samuelecancellieri** [comment]
Hi,
Yes, Crisprme is compatible with different nucleases, you must need to create the related PAM file with some constraint on position of the PAM sequence (downstream or upstream).
With regard of CFD, since the model cannot be used for PAM different them cas9 the software just put a placeholder value of - 1 as score, so any sorting is not altered by that and it will be done automatically on mm and bulges values.

Hope this will help.

Thanks,
